version: "3"
services:
  regresshelper:
    build: .
    container_name: regresshelper
    environment: 
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - SYSLOG_HOST=syslog
    depends_on:
      - mysql
      - syslog
    restart: always
    ports:
      - "8080"
  # metrics:
  #   image: hopsoft/graphite-statsd
  #   ports:
  #     - "80:80"
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports: 
      - "3306:3306"
  syslog:
    build: ./syslog/
    container_name: syslog-regress
    restart: always
    ports:
      - "514:514/udp"

  nginx:
    image: "nginx:alpine"
    container_name: regressnginx
    depends_on:
      - regresshelper
    ports:
      - "9010:9010"
    restart: always
    links:
      - regresshelper
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./public:/var/www/
      - ./auth/nginx.conf:/etc/nginx/nginx.conf
      - ./auth/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd
