swagger: '2.0'
info:
  title: RegressHelper API
  version: 1.0.0
basePath: /v1
paths:
  /testUsers:
    get: 
      responses:
        '200':
          description: all testUsers
          schema:
            type: array
            items: 
              type: object

    post:
      parameters:
        - name: productBody
          in: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
            required:
              - name
      responses:
        '201':
          description: Created