CREATE DATABASE IF NOT EXISTS `regress-helper` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE `regress-helper`;

CREATE TABLE IF NOT EXISTS `testUsers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `login` VARCHAR(500) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `user_id` VARCHAR(500) NOT NULL,
  `user_profile_id` VARCHAR(500) NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB;